// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JobAppTracker.Demo.MigrationsSQLite
{
    [DbContext(typeof(JobTrackerSQLLiteContext))]
    partial class JobTrackerSQLLiteContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.20");

            modelBuilder.Entity("JobAppTracker.Demo.Model.JobTracker", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("JobApplicationStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JobRefID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("JobRole")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("JobSummary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("JobType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("JobTrackerItems");
                });
#pragma warning restore 612, 618
        }
    }
}
